CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  lastName VARCHAR(500) NOT NULL,
  firstName VARCHAR(500) NOT NULL,
  emails JSON NOT NULL,
  phoneNumbers JSON NOT NULL
);

GRANT SELECT, INSERT, UPDATE, DELETE ON users TO ${dbAppUser};